### PR TITLE
Fix package name

### PR DESCRIPTION
**Pull request by codahale**
The mismatch between the repo name and the package name means it's awkward to import w/  `go get`. This moves `config.go` into a directory named `config`.

This way users can simply run:

```
go get github.com/nelhage/go.config
```

And then in their code:

``` go
import (
        "github.com/nelhage/go.config/config"
)

// ...

config.ParseConfig(etc)
```

As it stands without this patch, users would be required to rename the package:

``` go
import (
        config "github.com/nelhage/go.config"
)

config.ParseConfig(etc)
```

### CODE REVIEW

**Comment by codahale** [comment]
Also worth checking out is golint, which you can install via `go get -u github.com/golang/lint/golint`.

It has the following suggestions:

```
$ golint .
config.go:1:1: package comment should be of the form "Package config ..."
config.go:28:1: comment on exported function LoadConfig should be of the form "LoadConfig ..."
config.go:44:1: comment on exported function ParseConfig should be of the form "ParseConfig ..."
config.go:56:22: error strings should not be capitalized
config.go:63:22: error strings should not be capitalized
```

**Comment by codahale** [comment]
Oh, also check out your docs: http://godoc.org/github.com/nelhage/go.config.

godoc.org lazily pulls the source and builds the docs, so there's no "find someplace to host the docs" step here.

**Comment by nelhage** [comment]
Thanks for the comments! I'm worried I'm missing or misunderstanding something, though -- `go get` and imports seems to work fine for me as-is:

```
[nelhage@anarchique:~]$ export GOPATH=$(mktemp -d)
[nelhage@anarchique:~]$ go get github.com/nelhage/go.config
[nelhage@anarchique:~]$ cat > test.go
package main

import (
    "flag"
    "github.com/nelhage/go.config"
)

func main() {
    config.LoadConfig(flag.CommandLine, "test")
}
[nelhage@anarchique:~]$ go build test.go
[nelhage@anarchique:~]$ ./test
[nelhage@anarchique:~]$
```

I'll fix the golint warnings, though -- thanks.

**Comment by codahale** [comment]
Hmm, maybe it's fine. Folks on the mailing list were warning people off the current pattern.

_shrug_

**Comment by nelhage** [comment]
Do you have a link to the mailing-list post? Happy to change if this is recommended practice; I'd just like to understand the motivation :)

**Comment by codahale** [comment]
From [Organizing Go Code](http://blog.golang.org/organizing-go-code):

> The last element of the import path is typically the same as the package name. For instance, the import path "net/http" contains package http. This is not a requirement - you can make them different if you like - but you should follow the convention for predictability's sake: a user might be surprised that import "foo/bar" introduces the identifier quux into the package name space.

Also, I remembered that the IntelliJ plugin craps its pants when the package name and directory name don't line up.

**Comment by nelhage** [comment]
alright, fixed by merging this with some other stuff I'm writing (and will import shortly) so it is now `go.cli/config`

**Pull request closed without merging**
